[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sleep 3 && npm run db:migrate && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10