-- Constraint DDL for schema public
ALTER TABLE public.account ADD CONSTRAINT account_pkey PRIMARY KEY (id);
ALTER TABLE public.account ADD CONSTRAINT account_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE public.account_role_values ADD CONSTRAINT account_role_values_pkey PRIMARY KEY (value);
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_categories ADD CONSTRAINT ad_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_category_relationships ADD CONSTRAINT ad_category_relationships_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_clicks ADD CONSTRAINT ad_clicks_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_impressions ADD CONSTRAINT ad_impressions_pkey PRIMARY KEY (id);
ALTER TABLE public.admin_sessions ADD CONSTRAINT admin_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.admin_sessions ADD CONSTRAINT admin_sessions_session_id_key UNIQUE (session_id);
ALTER TABLE public.ads ADD CONSTRAINT ads_pkey PRIMARY KEY (id);
ALTER TABLE public.agreement_banner_dismissals ADD CONSTRAINT agreement_banner_dismissals_banner_version_id_fkey FOREIGN KEY (banner_version_id) REFERENCES agreement_versions(id);
ALTER TABLE public.agreement_banner_dismissals ADD CONSTRAINT agreement_banner_dismissals_pkey PRIMARY KEY (id);
ALTER TABLE public.agreement_banner_dismissals ADD CONSTRAINT agreement_banner_dismissals_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE public.agreement_versions ADD CONSTRAINT agreement_versions_content_hash_key UNIQUE (content_hash);
ALTER TABLE public.agreement_versions ADD CONSTRAINT agreement_versions_pkey PRIMARY KEY (id);
ALTER TABLE public.agreement_versions ADD CONSTRAINT agreement_versions_version_string_key UNIQUE (version_string);
ALTER TABLE public.api_key_usage ADD CONSTRAINT api_key_usage_api_key_id_fkey FOREIGN KEY (api_key_id) REFERENCES api_keys(id) ON DELETE CASCADE;
ALTER TABLE public.api_key_usage ADD CONSTRAINT api_key_usage_pkey PRIMARY KEY (id);
ALTER TABLE public.api_keys ADD CONSTRAINT api_keys_key_key UNIQUE (key);
ALTER TABLE public.api_keys ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);
ALTER TABLE public.api_keys ADD CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.api_logs ADD CONSTRAINT api_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.apikey ADD CONSTRAINT apikey_pkey PRIMARY KEY (id);
ALTER TABLE public.apikey ADD CONSTRAINT apikey_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE public.business_settings ADD CONSTRAINT business_settings_creator_id_creators_id_fk FOREIGN KEY (creator_id) REFERENCES creators(id);
ALTER TABLE public.business_settings ADD CONSTRAINT business_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.chat_sessions ADD CONSTRAINT chat_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.creators ADD CONSTRAINT creators_email_unique UNIQUE (email);
ALTER TABLE public.creators ADD CONSTRAINT creators_pkey PRIMARY KEY (id);
ALTER TABLE public.creators ADD CONSTRAINT creators_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES "user"(id);
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_global_unique UNIQUE (ad_type, placement, is_global_default);
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_relationship_ad_id_ads_id_fk FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE;
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_relationship_creator_id_ad_type_placement_key UNIQUE (creator_id, ad_type, placement);
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_relationship_pkey PRIMARY KEY (id);
ALTER TABLE public.session ADD CONSTRAINT session_pkey PRIMARY KEY (id);
ALTER TABLE public.session ADD CONSTRAINT session_token_key UNIQUE (token);
ALTER TABLE public.session ADD CONSTRAINT session_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE public."user" ADD CONSTRAINT user_email_key UNIQUE (email);
ALTER TABLE public."user" ADD CONSTRAINT user_pkey PRIMARY KEY (id);
ALTER TABLE public.user_agreements ADD CONSTRAINT user_agreements_agreement_version_id_fkey FOREIGN KEY (agreement_version_id) REFERENCES agreement_versions(id);
ALTER TABLE public.user_agreements ADD CONSTRAINT user_agreements_pkey PRIMARY KEY (id);
ALTER TABLE public.user_agreements ADD CONSTRAINT user_agreements_user_id_agreement_version_id_key UNIQUE (user_id, agreement_version_id);
ALTER TABLE public.user_agreements ADD CONSTRAINT user_agreements_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE public.users ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.verification ADD CONSTRAINT verification_pkey PRIMARY KEY (id);
ALTER TABLE public.verification_token ADD CONSTRAINT verification_token_identifier_token_pk PRIMARY KEY (identifier, token);
