-- Constraint DDL for schema public
ALTER TABLE public.account_role_values ADD CONSTRAINT account_role_values_pkey PRIMARY KEY (value);
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_advertiser_id_fkey FOREIGN KEY (advertiser_id) REFERENCES advertisers(id) ON DELETE CASCADE;
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_campaigns ADD CONSTRAINT chk_campaign_amounts_pos CHECK (budget_amount::numeric >= 0::numeric AND spent_amount::numeric >= 0::numeric);
ALTER TABLE public.ad_campaigns ADD CONSTRAINT chk_campaigns_dates CHECK (start_date < end_date);
ALTER TABLE public.ad_categories ADD CONSTRAINT ad_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_category_relationships ADD CONSTRAINT ad_category_relationships_ad_id_category_id_key UNIQUE (ad_id, category_id);
ALTER TABLE public.ad_category_relationships ADD CONSTRAINT ad_category_relationships_ad_id_fkey FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE;
ALTER TABLE public.ad_category_relationships ADD CONSTRAINT ad_category_relationships_category_id_fkey FOREIGN KEY (category_id) REFERENCES ad_categories(id) ON DELETE CASCADE;
ALTER TABLE public.ad_category_relationships ADD CONSTRAINT ad_category_relationships_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_clicks ADD CONSTRAINT ad_clicks_impression_id_fkey FOREIGN KEY (impression_id) REFERENCES ad_impressions(id) ON DELETE CASCADE;
ALTER TABLE public.ad_clicks ADD CONSTRAINT ad_clicks_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_impressions ADD CONSTRAINT ad_impressions_ad_id_fkey FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE SET NULL;
ALTER TABLE public.ad_impressions ADD CONSTRAINT ad_impressions_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE SET NULL;
ALTER TABLE public.ad_impressions ADD CONSTRAINT ad_impressions_impression_type_fk FOREIGN KEY (impression_type) REFERENCES impression_type_values(value);
ALTER TABLE public.ad_impressions ADD CONSTRAINT ad_impressions_mcp_tool_call_id_fkey FOREIGN KEY (mcp_tool_call_id) REFERENCES mcp_tool_calls(id);
ALTER TABLE public.ad_impressions ADD CONSTRAINT ad_impressions_message_ad_id_fkey FOREIGN KEY (message_ad_id) REFERENCES message_ads(id) ON DELETE SET NULL;
ALTER TABLE public.ad_impressions ADD CONSTRAINT ad_impressions_pkey PRIMARY KEY (id);
ALTER TABLE public.ad_impressions ADD CONSTRAINT ad_impressions_session_id_fkey FOREIGN KEY (session_id) REFERENCES chat_sessions(id);
ALTER TABLE public.ad_impressions ADD CONSTRAINT chk_impressions_amounts_pos CHECK (revenue_amount::numeric >= 0::numeric AND creator_payout_amount::numeric >= 0::numeric);
ALTER TABLE public.ad_impressions ADD CONSTRAINT fk_ad_impressions_queue FOREIGN KEY (ad_queue_session_id, ad_id, ad_queue_placement) REFERENCES ad_queue(chat_session_id, ad_id, placement) ON DELETE SET NULL;
ALTER TABLE public.ad_queue ADD CONSTRAINT ad_queue_ad_id_fkey FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE;
ALTER TABLE public.ad_queue ADD CONSTRAINT ad_queue_ad_type_check CHECK (ad_type = ANY (ARRAY['popup'::text, 'thinking'::text, 'banner'::text, 'video'::text]));
ALTER TABLE public.ad_queue ADD CONSTRAINT ad_queue_chat_session_id_fkey FOREIGN KEY (chat_session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.ad_queue ADD CONSTRAINT ad_queue_mcp_tool_call_id_fkey FOREIGN KEY (mcp_tool_call_id) REFERENCES mcp_tool_calls(id);
ALTER TABLE public.ad_queue ADD CONSTRAINT ad_queue_pkey PRIMARY KEY (chat_session_id, ad_id, placement);
ALTER TABLE public.ad_queue ADD CONSTRAINT ad_queue_placement_check CHECK (placement = ANY (ARRAY['sidebar'::text, 'modal'::text, 'inline'::text, 'overlay'::text, 'header'::text, 'footer'::text, 'default'::text]));
ALTER TABLE public.ads ADD CONSTRAINT ads_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.ads ADD CONSTRAINT ads_pkey PRIMARY KEY (id);
ALTER TABLE public.ads ADD CONSTRAINT banner_ads_image_required CHECK (ad_type <> 'banner'::ad_type OR image_url IS NOT NULL);
ALTER TABLE public.ads ADD CONSTRAINT trg_ads_campaign_active TRIGGER DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.advertiser_payments ADD CONSTRAINT advertiser_payments_advertiser_id_fkey FOREIGN KEY (advertiser_id) REFERENCES advertisers(id) ON DELETE CASCADE;
ALTER TABLE public.advertiser_payments ADD CONSTRAINT advertiser_payments_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.advertiser_payments ADD CONSTRAINT advertiser_payments_method_fk FOREIGN KEY (method) REFERENCES payment_method_values(value);
ALTER TABLE public.advertiser_payments ADD CONSTRAINT advertiser_payments_pkey PRIMARY KEY (id);
ALTER TABLE public.advertiser_status_values ADD CONSTRAINT advertiser_status_values_pkey PRIMARY KEY (value);
ALTER TABLE public.advertisers ADD CONSTRAINT advertisers_pkey PRIMARY KEY (id);
ALTER TABLE public.advertisers ADD CONSTRAINT advertisers_status_fk FOREIGN KEY (status) REFERENCES advertiser_status_values(value);
ALTER TABLE public.advertisers ADD CONSTRAINT advertisers_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.business_ad_type_preferences ADD CONSTRAINT business_ad_type_preferences_ad_type_check CHECK (ad_type::text = ANY (ARRAY['text'::character varying, 'banner'::character varying, 'video'::character varying, 'hyperlink'::character varying, 'popup'::character varying, 'thinking'::character varying]::text[]));
ALTER TABLE public.business_ad_type_preferences ADD CONSTRAINT business_ad_type_preferences_creator_id_ad_type_key UNIQUE (creator_id, ad_type);
ALTER TABLE public.business_ad_type_preferences ADD CONSTRAINT business_ad_type_preferences_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id);
ALTER TABLE public.business_ad_type_preferences ADD CONSTRAINT business_ad_type_preferences_pkey PRIMARY KEY (id);
ALTER TABLE public.business_category_preferences ADD CONSTRAINT business_category_preferences_category_id_fkey FOREIGN KEY (category_id) REFERENCES ad_categories(id);
ALTER TABLE public.business_category_preferences ADD CONSTRAINT business_category_preferences_creator_id_category_id_key UNIQUE (creator_id, category_id);
ALTER TABLE public.business_category_preferences ADD CONSTRAINT business_category_preferences_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id);
ALTER TABLE public.business_category_preferences ADD CONSTRAINT business_category_preferences_pkey PRIMARY KEY (id);
ALTER TABLE public.business_category_preferences ADD CONSTRAINT business_category_preferences_preference_check CHECK (preference::text = ANY (ARRAY['preferred'::character varying, 'allowed'::character varying, 'blocked'::character varying]::text[]));
ALTER TABLE public.business_settings ADD CONSTRAINT business_settings_ad_frequency_check CHECK (ad_frequency::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying]::text[]));
ALTER TABLE public.business_settings ADD CONSTRAINT business_settings_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id);
ALTER TABLE public.business_settings ADD CONSTRAINT business_settings_creator_id_key UNIQUE (creator_id);
ALTER TABLE public.business_settings ADD CONSTRAINT business_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.business_settings ADD CONSTRAINT business_settings_revenue_vs_relevance_check CHECK (revenue_vs_relevance >= 0.0 AND revenue_vs_relevance <= 1.0);
ALTER TABLE public.campaign_cpc_rates ADD CONSTRAINT campaign_cpc_rates_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_cpc_rates ADD CONSTRAINT campaign_cpc_rates_pkey PRIMARY KEY (id);
ALTER TABLE public.category_status_values ADD CONSTRAINT category_status_values_pkey PRIMARY KEY (value);
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.chat_sessions ADD CONSTRAINT chat_sessions_ad_frequency_check CHECK (ad_frequency::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying]::text[]));
ALTER TABLE public.chat_sessions ADD CONSTRAINT chat_sessions_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE;
ALTER TABLE public.chat_sessions ADD CONSTRAINT chat_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.chat_sessions ADD CONSTRAINT chat_sessions_revenue_vs_relevance_check CHECK (revenue_vs_relevance >= 0.0 AND revenue_vs_relevance <= 1.0);
ALTER TABLE public.chat_sessions ADD CONSTRAINT chat_sessions_session_type_check CHECK (session_type::text = ANY (ARRAY['mcp'::character varying, 'direct_chat'::character varying]::text[]));
ALTER TABLE public.chat_sessions ADD CONSTRAINT chk_sessions_dates CHECK (ended_at IS NULL OR started_at < ended_at);
ALTER TABLE public.content ADD CONSTRAINT content_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE;
ALTER TABLE public.content ADD CONSTRAINT content_pkey PRIMARY KEY (id);
ALTER TABLE public.content ADD CONSTRAINT content_status_fk FOREIGN KEY (status) REFERENCES content_status_values(value);
ALTER TABLE public.content_status_values ADD CONSTRAINT content_status_values_pkey PRIMARY KEY (value);
ALTER TABLE public.creator_advertiser_blocklists ADD CONSTRAINT creator_advertiser_blocklists_advertiser_id_fkey FOREIGN KEY (advertiser_id) REFERENCES advertisers(id) ON DELETE CASCADE;
ALTER TABLE public.creator_advertiser_blocklists ADD CONSTRAINT creator_advertiser_blocklists_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE;
ALTER TABLE public.creator_advertiser_blocklists ADD CONSTRAINT creator_advertiser_blocklists_pkey PRIMARY KEY (creator_id, advertiser_id);
ALTER TABLE public.creator_affiliate_codes ADD CONSTRAINT creator_affiliate_codes_advertiser_id_fkey FOREIGN KEY (advertiser_id) REFERENCES advertisers(id) ON DELETE CASCADE;
ALTER TABLE public.creator_affiliate_codes ADD CONSTRAINT creator_affiliate_codes_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE;
ALTER TABLE public.creator_affiliate_codes ADD CONSTRAINT creator_affiliate_codes_pkey PRIMARY KEY (id);
ALTER TABLE public.creator_affiliate_codes ADD CONSTRAINT creator_affiliate_codes_unique_creator_advertiser_program UNIQUE (creator_id, advertiser_id, affiliate_program);
ALTER TABLE public.creator_campaign_cpc_rates ADD CONSTRAINT creator_campaign_cpc_rates_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.creator_campaign_cpc_rates ADD CONSTRAINT creator_campaign_cpc_rates_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE;
ALTER TABLE public.creator_campaign_cpc_rates ADD CONSTRAINT creator_campaign_cpc_rates_pkey PRIMARY KEY (id);
ALTER TABLE public.creator_category_preferences ADD CONSTRAINT creator_category_preferences_category_id_fkey FOREIGN KEY (category_id) REFERENCES ad_categories(id) ON DELETE CASCADE;
ALTER TABLE public.creator_category_preferences ADD CONSTRAINT creator_category_preferences_creator_id_category_id_key UNIQUE (creator_id, category_id);
ALTER TABLE public.creator_category_preferences ADD CONSTRAINT creator_category_preferences_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE;
ALTER TABLE public.creator_category_preferences ADD CONSTRAINT creator_category_preferences_pkey PRIMARY KEY (id);
ALTER TABLE public.creator_category_preferences ADD CONSTRAINT creator_category_preferences_status_fk FOREIGN KEY (status) REFERENCES preference_status_values(value);
ALTER TABLE public.creator_settings ADD CONSTRAINT creator_settings_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE;
ALTER TABLE public.creator_settings ADD CONSTRAINT creator_settings_default_category_pref_fk FOREIGN KEY (default_category_pref) REFERENCES category_status_values(value);
ALTER TABLE public.creator_settings ADD CONSTRAINT creator_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.creators ADD CONSTRAINT creators_pkey PRIMARY KEY (id);
ALTER TABLE public.creators ADD CONSTRAINT creators_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_ad_type_check CHECK (ad_type = ANY (ARRAY['popup'::text, 'thinking'::text, 'banner'::text, 'video'::text]));
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_global_constraint CHECK (is_global_default = true AND creator_id IS NULL OR is_global_default = false AND creator_id IS NOT NULL);
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_global_unique UNIQUE (ad_type, placement, is_global_default) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_placement_check CHECK (placement = ANY (ARRAY['sidebar'::text, 'modal'::text, 'inline'::text, 'overlay'::text, 'header'::text, 'footer'::text, 'default'::text]));
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_relationship_ad_id_fkey FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE;
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_relationship_creator_id_ad_type_placement_key UNIQUE (creator_id, ad_type, placement);
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_relationship_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE;
ALTER TABLE public.default_ad_relationship ADD CONSTRAINT default_ad_relationship_pkey PRIMARY KEY (id);
ALTER TABLE public.effective_cpc_rates ADD CONSTRAINT effective_cpc_rates_pkey PRIMARY KEY (creator_id, campaign_id, placement, ad_type);
ALTER TABLE public.embeddings ADD CONSTRAINT chk_embeddings_source_table CHECK (source_table = ANY (ARRAY['content'::text, 'ads'::text]));
ALTER TABLE public.embeddings ADD CONSTRAINT embeddings_pkey PRIMARY KEY (source_table, source_id, chunk_id);
ALTER TABLE public.embeddings ADD CONSTRAINT trg_embeddings_source_fk TRIGGER DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.impression_type_values ADD CONSTRAINT impression_type_values_pkey PRIMARY KEY (value);
ALTER TABLE public.mcp_tool_call_queries ADD CONSTRAINT mcp_tool_call_queries_mcp_tool_call_id_fkey FOREIGN KEY (mcp_tool_call_id) REFERENCES mcp_tool_calls(id) ON DELETE CASCADE;
ALTER TABLE public.mcp_tool_call_queries ADD CONSTRAINT mcp_tool_call_queries_mcp_tool_call_id_query_order_key UNIQUE (mcp_tool_call_id, query_order);
ALTER TABLE public.mcp_tool_call_queries ADD CONSTRAINT mcp_tool_call_queries_pkey PRIMARY KEY (id);
ALTER TABLE public.mcp_tool_call_queries ADD CONSTRAINT mcp_tool_call_queries_query_order_check CHECK (query_order >= 1 AND query_order <= 3);
ALTER TABLE public.mcp_tool_calls ADD CONSTRAINT mcp_tool_calls_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES chat_sessions(id);
ALTER TABLE public.mcp_tool_calls ADD CONSTRAINT mcp_tool_calls_pkey PRIMARY KEY (id);
ALTER TABLE public.message_ads ADD CONSTRAINT chk_message_ads_slot CHECK (slot > 0);
ALTER TABLE public.message_ads ADD CONSTRAINT message_ads_ad_id_fkey FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE;
ALTER TABLE public.message_ads ADD CONSTRAINT message_ads_message_id_ad_id_placement_slot_key UNIQUE (message_id, ad_id, placement, slot);
ALTER TABLE public.message_ads ADD CONSTRAINT message_ads_message_id_fkey FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE;
ALTER TABLE public.message_ads ADD CONSTRAINT message_ads_pkey PRIMARY KEY (id);
ALTER TABLE public.message_ads ADD CONSTRAINT message_ads_unique_slot_per_message UNIQUE (message_id, placement, slot);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.payment_method_values ADD CONSTRAINT payment_method_values_pkey PRIMARY KEY (value);
ALTER TABLE public.payouts ADD CONSTRAINT chk_payouts_period CHECK (period_start < period_end);
ALTER TABLE public.payouts ADD CONSTRAINT payouts_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creators(id) ON DELETE CASCADE;
ALTER TABLE public.payouts ADD CONSTRAINT payouts_pkey PRIMARY KEY (id);
ALTER TABLE public.preference_status_values ADD CONSTRAINT preference_status_values_pkey PRIMARY KEY (value);
ALTER TABLE public.session_ad_type_overrides ADD CONSTRAINT session_ad_type_overrides_ad_type_check CHECK (ad_type::text = ANY (ARRAY['text'::character varying, 'banner'::character varying, 'video'::character varying, 'hyperlink'::character varying, 'popup'::character varying, 'thinking'::character varying]::text[]));
ALTER TABLE public.session_ad_type_overrides ADD CONSTRAINT session_ad_type_overrides_pkey PRIMARY KEY (id);
ALTER TABLE public.session_ad_type_overrides ADD CONSTRAINT session_ad_type_overrides_session_id_ad_type_key UNIQUE (session_id, ad_type);
ALTER TABLE public.session_ad_type_overrides ADD CONSTRAINT session_ad_type_overrides_session_id_fkey FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_role_fk FOREIGN KEY (role) REFERENCES account_role_values(value);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
