-- Non-constraint index DDL for schema public
CREATE UNIQUE INDEX ad_campaigns_name_unique_idx ON ad_campaigns USING btree (name) WHERE deleted_at IS NULL;
CREATE INDEX idx_ad_campaigns_advertiser_status ON ad_campaigns USING btree (advertiser_id, status) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_campaigns_name_active ON ad_campaigns USING btree (name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX ad_categories_name_unique_idx ON ad_categories USING btree (name);
CREATE INDEX idx_ad_category_relationships_ad_cat ON ad_category_relationships USING btree (ad_id, category_id);
CREATE INDEX idx_ad_clicks_billed_status ON ad_clicks USING btree (impression_id, is_billed, created_at);
CREATE INDEX idx_ad_clicks_impression_created ON ad_clicks USING btree (impression_id, created_at);
CREATE UNIQUE INDEX idx_ad_clicks_one_billed_per_impression ON ad_clicks USING btree (impression_id) WHERE is_billed = true;
CREATE INDEX ad_impressions_queue_idx ON ad_impressions USING btree (ad_queue_session_id, ad_id, ad_queue_placement);
CREATE INDEX idx_ad_impressions_ad ON ad_impressions USING btree (ad_id);
CREATE INDEX idx_ad_impressions_creator ON ad_impressions USING btree (creator_id);
CREATE INDEX idx_ad_impressions_creator_created ON ad_impressions USING btree (creator_id, created_at);
CREATE INDEX ad_queue_available_idx ON ad_queue USING btree (chat_session_id, ad_type, placement, similarity DESC);
CREATE INDEX ad_queue_times_served_idx ON ad_queue USING btree (times_served, similarity DESC);
CREATE INDEX idx_ads_campaign ON ads USING btree (campaign_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_advertiser_payments_advertiser ON advertiser_payments USING btree (advertiser_id);
CREATE INDEX idx_advertiser_payments_campaign ON advertiser_payments USING btree (campaign_id);
CREATE INDEX idx_advertiser_payments_received ON advertiser_payments USING btree (received_at DESC);
CREATE UNIQUE INDEX advertisers_name_unique_idx ON advertisers USING btree (name) WHERE deleted_at IS NULL;
CREATE INDEX idx_business_ad_type_preferences_creator_id ON business_ad_type_preferences USING btree (creator_id);
CREATE INDEX idx_business_ad_type_preferences_enabled ON business_ad_type_preferences USING btree (creator_id, is_enabled);
CREATE INDEX idx_business_category_preferences_creator_id ON business_category_preferences USING btree (creator_id);
CREATE INDEX idx_business_category_preferences_preference ON business_category_preferences USING btree (creator_id, preference);
CREATE INDEX idx_business_settings_creator_id ON business_settings USING btree (creator_id);
CREATE INDEX idx_business_settings_is_active ON business_settings USING btree (is_active);
CREATE INDEX idx_campaign_cpc_rates_lookup ON campaign_cpc_rates USING btree (campaign_id, placement, ad_type);
CREATE INDEX idx_chat_messages_session_created ON chat_messages USING btree (session_id, created_at);
CREATE INDEX idx_chat_sessions_active ON chat_sessions USING btree (creator_id, visitor_uuid) WHERE ended_at IS NULL;
CREATE INDEX idx_chat_sessions_creator_activity ON chat_sessions USING btree (creator_id, last_activity_at);
CREATE INDEX idx_chat_sessions_creator_started ON chat_sessions USING btree (creator_id, started_at);
CREATE INDEX idx_chat_sessions_creator_visitor ON chat_sessions USING btree (creator_id, visitor_uuid) WHERE ended_at IS NULL;
CREATE INDEX idx_chat_sessions_last_activity ON chat_sessions USING btree (last_activity_at);
CREATE INDEX idx_chat_sessions_run_id ON chat_sessions USING btree (run_id);
CREATE INDEX idx_chat_sessions_session_type ON chat_sessions USING btree (session_type);
CREATE INDEX idx_content_creator ON content USING btree (creator_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_creator_affiliate_codes_active ON creator_affiliate_codes USING btree (creator_id, advertiser_id);
CREATE INDEX idx_creator_affiliate_codes_advertiser ON creator_affiliate_codes USING btree (advertiser_id);
CREATE INDEX idx_creator_affiliate_codes_advertiser_active ON creator_affiliate_codes USING btree (advertiser_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_creator_affiliate_codes_creator ON creator_affiliate_codes USING btree (creator_id);
CREATE INDEX idx_creator_affiliate_codes_creator_active ON creator_affiliate_codes USING btree (creator_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_creator_affiliate_codes_creator_advertiser_active ON creator_affiliate_codes USING btree (creator_id, advertiser_id) WHERE is_active = true AND deleted_at IS NULL;
CREATE INDEX idx_creator_campaign_cpc_rates_lookup ON creator_campaign_cpc_rates USING btree (creator_id, campaign_id, placement, ad_type);
CREATE INDEX idx_creator_category_prefs_category ON creator_category_preferences USING btree (category_id);
CREATE INDEX idx_creator_category_prefs_creator ON creator_category_preferences USING btree (creator_id);
CREATE INDEX idx_creator_category_prefs_creator_cat ON creator_category_preferences USING btree (creator_id, category_id);
CREATE INDEX idx_creator_settings_creator ON creator_settings USING btree (creator_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX creators_name_unique_idx ON creators USING btree (name);
CREATE INDEX default_ad_creator_lookup_idx ON default_ad_relationship USING btree (creator_id, ad_type, placement) WHERE creator_id IS NOT NULL;
CREATE INDEX default_ad_global_lookup_idx ON default_ad_relationship USING btree (ad_type, placement) WHERE is_global_default = true;
CREATE INDEX idx_embeddings_ann ON embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists='100');
CREATE INDEX idx_embeddings_embedding ON embeddings USING ivfflat (embedding) WITH (lists='100');
CREATE INDEX idx_message_ads_ad ON message_ads USING btree (ad_id);
CREATE INDEX idx_notifications_user_created ON notifications USING btree (user_id, created_at);
CREATE INDEX idx_notifications_user_unread ON notifications USING btree (user_id, read_at) WHERE read_at IS NULL;
CREATE INDEX idx_payouts_creator ON payouts USING btree (creator_id);
CREATE INDEX idx_payouts_creator_period ON payouts USING btree (creator_id, period_start, period_end);
CREATE INDEX idx_session_ad_type_overrides_enabled ON session_ad_type_overrides USING btree (session_id, is_enabled);
CREATE INDEX idx_session_ad_type_overrides_session_id ON session_ad_type_overrides USING btree (session_id);
CREATE UNIQUE INDEX idx_users_email ON users USING btree (email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_users_email_active ON users USING btree (email) WHERE deleted_at IS NULL;
